<a href="https://colab.research.google.com/github/ewarren38/HW6_WarrenE/blob/main/HW6_WarrenE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Homework 6**
**Author:** Eleanor Warren

**Course:** ST554-601

**Purpose:** Complete HW 6

**Date:** 3.10.26

##**Part 1 | Querying Databases**

First I'm estalblishing a connection to the Lahman baseball database, and then returning a pandas dataframe, `schema_df`, with all the tables in the database.

In [17]:
import pandas as pd
import sqlite3
con = sqlite3.connect("/content/lahman_1871-2022.sqlite")
get_schema = '''
   SELECT *
   FROM sqlite_schema
   WHERE type = 'table';
   '''
schema_df = pd.read_sql(get_schema, con)
schema_df #.iloc[13,4]

# The simple querying structure:
# pd.read_sql("SELECT ... FROM ... WHERE...;", con) using con from above.

,type,name,tbl_name,rootpage,sql
0,table,AllstarFull,AllstarFull,2,"CREATE TABLE AllstarFull (\nplayerID TEXT,\nye..."
1,table,Appearances,Appearances,3,"CREATE TABLE Appearances (\nyearID INTEGER,\nt..."
2,table,AwardsManagers,AwardsManagers,4,"CREATE TABLE AwardsManagers (\nplayerID TEXT,\..."
3,table,AwardsPlayers,AwardsPlayers,5,"CREATE TABLE AwardsPlayers (\nplayerID TEXT,\n..."
4,table,AwardsShareManagers,AwardsShareManagers,6,CREATE TABLE AwardsShareManagers (\nawardID TE...
5,table,AwardsSharePlayers,AwardsSharePlayers,7,CREATE TABLE AwardsSharePlayers (\nawardID TEX...
6,table,Batting,Batting,8,"CREATE TABLE Batting (\nplayerID TEXT,\nyearID..."
7,table,BattingPost,BattingPost,9,"CREATE TABLE BattingPost (\nyearID INTEGER,\nr..."
8,table,CollegePlaying,CollegePlaying,10,"CREATE TABLE CollegePlaying (\nplayerID TEXT,\..."
9,table,Fielding,Fielding,11,"CREATE TABLE Fielding (\nplayerID TEXT,\nyearI..."
10,table,FieldingOF,FieldingOF,12,"CREATE TABLE FieldingOF (\nplayerID TEXT,\nyea..."
11,table,FieldingOFsplit,FieldingOFsplit,13,"CREATE TABLE FieldingOFsplit (\nplayerID TEXT,..."
12,table,FieldingPost,FieldingPost,14,"CREATE TABLE FieldingPost (\nplayerID TEXT,\ny..."
13,table,HallOfFame,HallOfFame,15,"CREATE TABLE HallOfFame (\nplayerID TEXT,\nyea..."
14,table,HomeGames,HomeGames,16,"CREATE TABLE HomeGames (\nyearkey INTEGER,\nle..."
15,table,Managers,Managers,17,"CREATE TABLE Managers (\nplayerID TEXT,\nyearI..."
16,table,ManagersHalf,ManagersHalf,18,"CREATE TABLE ManagersHalf (\nplayerID TEXT,\ny..."
17,table,Parks,Parks,19,"CREATE TABLE Parks (\nID INTEGER,\nparkalias T..."
18,table,People,People,21,"CREATE TABLE People (\nID INTEGER,\nplayerID T..."
19,table,Pitching,Pitching,23,"CREATE TABLE Pitching (\nplayerID TEXT,\nyearI..."
20,table,PitchingPost,PitchingPost,24,"CREATE TABLE PitchingPost (\nplayerID TEXT,\ny..."
21,table,Salaries,Salaries,25,"CREATE TABLE Salaries (\nyearID INTEGER,\nteam..."
22,table,Schools,Schools,26,"CREATE TABLE Schools (\nschoolID TEXT,\nname_f..."
23,table,SeriesPost,SeriesPost,27,"CREATE TABLE SeriesPost (\nyearID INTEGER,\nro..."
24,table,Teams,Teams,28,"CREATE TABLE Teams (\nyearID INTEGER,\nlgID TE..."
25,table,TeamsFranchises,TeamsFranchises,29,"CREATE TABLE TeamsFranchises (\nfranchID TEXT,..."
26,table,TeamsHalf,TeamsHalf,30,"CREATE TABLE TeamsHalf (\nyearID INTEGER,\nlgI..."

Again, since I know I'll be making multiple queries, I'm going to use the in-class example for creating a helper function.

In [14]:
#PROBABLY DELETE

#Make a querying function
def execute_query(connection, query):
    cursor = connection.cursor()
    try:
      cursor.execute(query)
      print("Query executed successfully")
    except Error as e:
      print(f"The error {e} occurred")
    cursor.close()

2. Construct a table of hall of fame pitchers (any hall of famer that pitched) with their `playerID` and sum for `GS, G, W, L, IPOuts, CG, SHO, SV`.

We need to merge together information from the Pitching and the HallOfFame tables.

In [21]:
pitch_stats = pd.read_sql("""
  SELECT DISTINCT p.playerID, sum(GS), sum(G), sum(W), sum(L), sum(IPOuts), sum(CG), sum(SHO), sum(SV)
  FROM Pitching AS p
  INNER join HallOfFame AS h ON h.playerID = p.playerID
  WHERE inducted = 'Y'
  GROUP BY p.playerID
  ORDER BY p.playerID;
  """, con)

pitch_stats

,playerID,sum(GS),sum(G),sum(W),sum(L),sum(IPOuts),sum(CG),sum(SHO),sum(SV)
0,alexape01,599,696,373,208,15570,437,90,32
1,ansonca01,0,3,0,1,12,0,0,1
2,becklja01,1,1,0,1,12,0,0,0
3,bendech01,334,459,212,127,9051,255,40,34
4,blylebe01,685,692,287,250,14910,242,60,0
...,...,...,...,...,...,...,...,...,...
103,willivi01,471,513,249,205,11988,388,50,11
104,wrighge01,0,3,0,1,15,0,0,0
105,wrighha01,8,36,4,4,301,0,0,14
106,wynnea01,612,691,300,244,13692,290,49,15
107,youngcy01,815,906,511,315,22068,749,76,18